FROM artifact.samsungds.net/devops-template-docker/baseimage/python:3.10
ENV PATH $HOME/.local/bin:$PATH

RUN sudo mkdir /project && sudo chown devops:devops /project
COPY . /project/

RUN pip install -U pip
RUN pip install -U setuptools
RUN pip install -r /project/requirements.txt

#WORKDIR /root
#RUN echo 'alias python=python3.10' >> .bashrc

WORKDIR /project

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
